### ISSUE TITLE
Infografía_realidadAumentada

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-ElisabetRD#1]
[Infografía_RojasDguez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-ElisabetRD/files/14212645/Infografia_RojasDguez.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
